openapi: 3.0.1
info:
  title: iBoard 社區公佈欄(後端Spring boot)
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: 住戶 CRUD
- name: 管理員 CRUD
paths:
  /users/{userId}:
    get:
      tags:
      - 住戶 CRUD
      summary: 取得住戶資料
      description: 透過userId取得住戶資料並回傳前端
      operationId: getUserById
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags:
      - 住戶 CRUD
      summary: 修改住戶資料
      description: 透過 userId 修改住戶資料
      operationId: updateUser
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        "404":
          description: 無此 住戶 ID，無法執行修改功能
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Admin'
    delete:
      tags:
      - 住戶 CRUD
      summary: 刪除住戶資料
      description: 透過 userId 刪除住戶資料
      operationId: deleteUser
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
  /board/{boardId}:
    get:
      tags:
      - board-controller
      summary: 取得公佈欄資料
      description: 透過board_id取得公佈欄資料
      operationId: getBoardById
      parameters:
      - name: boardId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Board'
    put:
      tags:
      - board-controller
      summary: 修改公佈欄訊息
      description: 透過 boardId 查詢訊息後修改訊息
      operationId: updateBoard
      parameters:
      - name: boardId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BoardRequest'
        required: true
      responses:
        "404":
          description: 無此 公佈欄訊息 ID，無法執行修改功能
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Board'
    delete:
      tags:
      - board-controller
      summary: 刪除公佈欄訊息
      description: 透過 boardId 刪除已存在訊息
      operationId: deleteBoard
      parameters:
      - name: boardId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Board'
  /admins/{adminId}:
    get:
      tags:
      - 管理員 CRUD
      summary: 透過adminId查詢管理員資料
      description: 透過adminId查詢管理員資料
      operationId: getAdminById
      parameters:
      - name: adminId
        in: path
        description: 管理員 ID 編號
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "404":
          description: '無此管理員 ID '
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Admin'
    put:
      tags:
      - 管理員 CRUD
      summary: 修改管理員資料
      description: 透過adminId先查詢是否存在，如存在該筆數據，執行修改；最後再使用adminId重新查詢該筆數據後回傳
      operationId: updateAdmin
      parameters:
      - name: adminId
        in: path
        description: 管理員 ID 編號
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminRequest'
        required: true
      responses:
        "404":
          description: 無此管理員 ID
        "200":
          description: OK
          content:
            application/json: {}
    delete:
      tags:
      - 管理員 CRUD
      summary: 刪除管理員資料
      description: 透過adminId刪除管理員資料
      operationId: deleteAdmin
      parameters:
      - name: adminId
        in: path
        description: 管理員 ID 編號
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /users:
    get:
      tags:
      - 住戶 CRUD
      summary: 住戶資料列表(模糊查詢+分頁+排序)
      description: 可模糊查詢姓名，依照前端請求orderBy指定項目排序(預設為創建資料時間)，依照前端請求sort指定排序順序(DESC由大到小排序)，依照前端請求limit限制每頁筆數(預設5)，依照前端請求offset設定跳過筆數(預設0，代表第一頁)。回傳總數count讓前端計算分頁。
      operationId: getUsers
      parameters:
      - name: search
        in: query
        required: false
        schema:
          type: string
      - name: orderBy
        in: query
        required: false
        schema:
          type: string
          default: created_date
      - name: sort
        in: query
        required: false
        schema:
          type: string
          default: desc
      - name: limit
        in: query
        required: false
        schema:
          maximum: 1000
          minimum: 0
          type: integer
          format: int32
          default: 5
      - name: offset
        in: query
        required: false
        schema:
          minimum: 0
          type: integer
          format: int32
          default: 0
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageUser'
    post:
      tags:
      - 住戶 CRUD
      summary: 新增住戶資料
      description: 新增住戶資料，完成後回傳新增的住戶資訊
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
  /board:
    get:
      tags:
      - board-controller
      summary: 取得所有公佈欄資訊
      description: 取得所有公佈欄資訊
      operationId: getBoards
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Board'
    post:
      tags:
      - board-controller
      summary: 新增公佈欄訊息
      description: 新增公佈欄訊息
      operationId: createBoard
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BoardRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Board'
  /admins:
    get:
      tags:
      - 管理員 CRUD
      summary: 取得所有管理員
      description: 取得所有管理員資料
      operationId: getAdmins
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Admin'
    post:
      tags:
      - 管理員 CRUD
      summary: 新增管理員資料
      description: 新增管理員資料
      operationId: createAdmin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Admin'
components:
  schemas:
    UserRequest:
      required:
      - userAddress
      - userName
      - userTel
      type: object
      properties:
        userFaceId:
          type: string
          description: 住戶 ID
        userName:
          type: string
          description: 住戶姓名
        userTel:
          type: string
          description: 住戶聯絡電話
        userAddress:
          type: string
          description: 住戶住址
    Admin:
      type: object
      properties:
        adminId:
          type: integer
          description: 管理員 ID
          format: int32
        adminAccount:
          type: string
          description: 管理員帳號
        adminPassword:
          type: string
          description: 管理員密碼
        adminName:
          type: string
          description: 管理員姓名
        adminTel:
          type: string
          description: 管理員電話
        adminEmail:
          type: string
          description: 管理員 email
        adminAddress:
          type: string
          description: 管理員地址
        createdDate:
          type: string
          description: 管理員資料被創建時間
          format: date-time
        lastModifiedDate:
          type: string
          description: 管理員資料最後修改時間
          format: date-time
    BoardRequest:
      required:
      - boardCategory
      - boardDescription
      - boardTitle
      type: object
      properties:
        boardCategory:
          type: string
          description: 訊息分類
          enum:
          - IMPORTANT
          - ADVERTISE
          - ACTIVITY
          - ANNOUNCEMENT
        boardTitle:
          type: string
          description: 公告title
        boardDescription:
          type: string
          description: 公告內容
    Board:
      type: object
      properties:
        boardId:
          type: integer
          description: 公佈欄 ID
          format: int32
        boardCategory:
          type: string
          description: 公佈欄 分類
          enum:
          - IMPORTANT
          - ADVERTISE
          - ACTIVITY
          - ANNOUNCEMENT
        boardTitle:
          type: string
          description: '公佈欄 標題 '
        boardDescription:
          type: string
          description: 公佈欄 內容文字
        createdDate:
          type: string
          description: 公佈欄 被創建時間
          format: date-time
        lastModifiedDate:
          type: string
          description: 公佈欄 最後被修改時間
          format: date-time
    AdminRequest:
      required:
      - adminAccount
      - adminAddress
      - adminEmail
      - adminName
      - adminPassword
      - adminTel
      type: object
      properties:
        adminAccount:
          type: string
          description: 管理員帳號
        adminPassword:
          type: string
          description: 管理員密碼
        adminName:
          type: string
          description: 管理員姓名
        adminTel:
          type: string
          description: 管理員電話
        adminEmail:
          type: string
          description: 管理員信箱
        adminAddress:
          type: string
          description: 管理員地址
    User:
      type: object
      properties:
        userId:
          type: integer
          description: 住戶 ID
          format: int32
        userFaceId:
          type: string
          description: 住戶 人臉辨識 ID
        userName:
          type: string
          description: 住戶姓名
        userTel:
          type: string
          description: 住戶聯絡電話
        userAddress:
          type: string
          description: 住戶地址
        createdDate:
          type: string
          description: 住戶資料被建立時間
          format: date-time
        lastModifiedDate:
          type: string
          description: 住戶資料最後修改時間
          format: date-time
    PageUser:
      type: object
      properties:
        limit:
          type: integer
          description: 限制資料庫回傳筆數(每個分頁要顯示幾筆數據)
          format: int32
        offset:
          type: integer
          description: 跳過幾筆數據(例如limit預設=5，第一頁offset=0，第二頁offset=5....)
          format: int32
        total:
          type: integer
          description: 查詢結果筆數，計算分頁數量用
          format: int32
        results:
          type: array
          description: 住戶資料集
          items:
            $ref: '#/components/schemas/User'
